### ISSUE TITLE
volume max issue

### ISSUE THREAD

**Issue by mjm716** [stuerp/foo_uie_webview#11]
This has previously been called out in this thread.
https://hydrogenaud.io/index.php/topic,126042.msg1050146.html#msg1050146

please fix your default Template.html or the component before you fuck someone's speakers!

problem:
create new webview instance in empty panel.
FB volume shoots to 100%.

btw, if left in layout, Template.html continues to trigger max volume at points while playing. 

really not cool.

**Comment by stuerp** [comment]
I commented it out in the next version,
