### ISSUE TITLE
0.1.5.6 template setting software lost settings after restarting

### ISSUE THREAD

**Issue by fszok** [stuerp/foo_uie_webview#7]
v0.1.5.6 will cause template settings to be lost. After setting them, close foobar2000 and then open the software. The last settings will be lost. There is no way but to return to the preview version. Please fix this problem, thank you.

**Comment by stuerp** [comment]
0.1.5.6 always clears the browsing data on startup. 0.1.6.0 has on option to disable that.

**Comment by stuerp** [comment]
Fixed in 0.1.6.0.
